### PR TITLE
Birthday Reminder script

### PR DESCRIPTION
**Pull request by VAJRESH**
Notifies every 12 hours.
You can add new entries, search for particular name, see all entries all from the python program

### CODE REVIEW

**Comment by VAJRESH** [comment]
please add hacktoberfest-accepted label to this pull request.
I am a total beginner in this field and this is one of my first projects along with 2 others.
Thanks for the help.

**Comment by keshavsingh3197** [comment]
i have merged your pull request so no need to label it.
both merging and labeling are acceptable by hacktoberfest

**Comment by VAJRESH** [comment]
Thanks for merging.
I thought you will not merge that's why I asked for labelling.
Thanks again

**Comment by VAJRESH** [comment]
no
I'll keep it fork as I can see others like me and If possible I'll help too

**Pull request merged**
